{{ if .Values.tridentbackendconfig.enabled }}
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: trident-backend-config-default
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  {{ .Values.tridentbackendconfig.config | toYaml | indent 2 | trim }}
{{ end }}