prometheus:
  alertmanager:
    enabled: false

  extraScrapeConfigs: |
    - job_name: 'prometheus-blackbox-exporter'
      scrape_interval: 1s
      scrape_timeout: 1s
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - https://onet.pl
          - https://cert-lu-myremote.tech.ec.europa.eu
          - https://wp.pl
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: prometheus-blackbox-exporter:9115
    - job_name: 'prometheus-blackbox-exporter-icmp'
      scrape_interval: 1s
      scrape_timeout: 1s
      metrics_path: /probe
      params:
        module: [icmp]
      static_configs:
        - targets:
          - onet.pl
          - cert-lu-myremote.tech.ec.europa.eu
          - wp.pl
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: prometheus-blackbox-exporter:9115
    - job_name: 'prometheus-blackbox-exporter-tcp'
      scrape_interval: 1s
      scrape_timeout: 1s
      metrics_path: /probe
      params:
        module: [tcp]
      static_configs:
        - targets:
          - onet.pl
          - cert-lu-myremote.tech.ec.europa.eu
          - wp.pl
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: prometheus-blackbox-exporter:9115
